spring.application.name=userinfoserver
mybatis.mapper-locations=classpath:db/mapper/*.xml

spring.datasource.url=${DB_URL:jdbc:mariadb://localhost:3307/app_target?useUnicode=true&characterEncoding=utf8}
spring.datasource.username=${DB_USER:app_target}
spring.datasource.password=${DB_PASSWORD:app_target1234}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
